2022-07-25 00:37:32,232 INFO    MainThread:2470683 [internal.py:wandb_internal():90] W&B internal server running at pid: 2470683, started at: 2022-07-25 00:37:32.229540
2022-07-25 00:37:32,257 INFO    WriterThread:2470683 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220725_003730-joivm36e/run-joivm36e.wandb
2022-07-25 00:37:32,258 DEBUG   HandlerThread:2470683 [handler.py:handle_request():141] handle_request: run_start
2022-07-25 00:37:32,309 DEBUG   HandlerThread:2470683 [meta.py:__init__():35] meta init
2022-07-25 00:37:32,309 DEBUG   HandlerThread:2470683 [meta.py:__init__():49] meta init done
2022-07-25 00:37:32,309 DEBUG   HandlerThread:2470683 [meta.py:probe():209] probe
2022-07-25 00:37:32,326 DEBUG   HandlerThread:2470683 [meta.py:_setup_git():199] setup git
2022-07-25 00:37:32,441 DEBUG   HandlerThread:2470683 [meta.py:_setup_git():206] setup git done
2022-07-25 00:37:32,442 DEBUG   HandlerThread:2470683 [meta.py:_save_pip():53] save pip
2022-07-25 00:37:32,447 DEBUG   HandlerThread:2470683 [meta.py:_save_pip():67] save pip done
2022-07-25 00:37:32,449 DEBUG   HandlerThread:2470683 [meta.py:_save_conda():74] save conda
2022-07-25 00:37:47,483 DEBUG   HandlerThread:2470683 [meta.py:_save_conda():84] save conda done
2022-07-25 00:37:47,483 DEBUG   HandlerThread:2470683 [meta.py:probe():247] probe done
2022-07-25 00:37:49,288 WARNING MainThread:2470683 [internal.py:is_dead():387] Internal process exiting, parent pid 2470651 disappeared
2022-07-25 00:37:49,288 ERROR   MainThread:2470683 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-25 00:37:50,167 INFO    HandlerThread:2470683 [handler.py:finish():806] shutting down handler
2022-07-25 00:37:50,167 INFO    WriterThread:2470683 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220725_003730-joivm36e/run-joivm36e.wandb
2022-07-25 00:37:50,258 INFO    SenderThread:2470683 [sender.py:finish():1111] shutting down sender
2022-07-25 00:37:50,258 INFO    MainThread:2470683 [internal.py:handle_exit():80] Internal process exited
