2022-07-27 17:10:06,769 INFO    MainThread:2932666 [internal.py:wandb_internal():90] W&B internal server running at pid: 2932666, started at: 2022-07-27 17:10:06.766440
2022-07-27 17:10:06,780 INFO    WriterThread:2932666 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220727_171004-3b4mwtf2/run-3b4mwtf2.wandb
2022-07-27 17:10:06,781 DEBUG   HandlerThread:2932666 [handler.py:handle_request():141] handle_request: run_start
2022-07-27 17:10:06,825 DEBUG   HandlerThread:2932666 [meta.py:__init__():35] meta init
2022-07-27 17:10:06,825 DEBUG   HandlerThread:2932666 [meta.py:__init__():49] meta init done
2022-07-27 17:10:06,825 DEBUG   HandlerThread:2932666 [meta.py:probe():209] probe
2022-07-27 17:10:06,842 DEBUG   HandlerThread:2932666 [meta.py:_setup_git():199] setup git
2022-07-27 17:10:06,962 DEBUG   HandlerThread:2932666 [meta.py:_setup_git():206] setup git done
2022-07-27 17:10:06,962 DEBUG   HandlerThread:2932666 [meta.py:_save_pip():53] save pip
2022-07-27 17:10:06,970 DEBUG   HandlerThread:2932666 [meta.py:_save_pip():67] save pip done
2022-07-27 17:10:06,971 DEBUG   HandlerThread:2932666 [meta.py:_save_conda():74] save conda
2022-07-27 17:10:15,558 DEBUG   HandlerThread:2932666 [meta.py:_save_conda():84] save conda done
2022-07-27 17:10:15,558 DEBUG   HandlerThread:2932666 [meta.py:probe():247] probe done
2022-07-27 17:10:15,784 WARNING MainThread:2932666 [internal.py:is_dead():387] Internal process exiting, parent pid 2877937 disappeared
2022-07-27 17:10:15,784 ERROR   MainThread:2932666 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-27 17:10:15,784 INFO    WriterThread:2932666 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220727_171004-3b4mwtf2/run-3b4mwtf2.wandb
2022-07-27 17:10:15,790 INFO    SenderThread:2932666 [sender.py:finish():1111] shutting down sender
2022-07-27 17:10:16,206 INFO    HandlerThread:2932666 [handler.py:finish():806] shutting down handler
2022-07-27 17:10:16,207 INFO    MainThread:2932666 [internal.py:handle_exit():80] Internal process exited
